language: python
python:
  - "3.4"
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "gem install dpl"
script:
  - py.test -v --cov-report term-missing --cov=weppy_mvc_demo -r w tests
after_success:
  - coveralls
