branch-defaults:
  master:
    environment: weppy-mvc-demo-dev
global:
  application_name: weppy-mvc-demo
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1
  default_region: us-east-1
  profile: null
  sc: git
